"""
English-to-Hebrew ingredient dictionary.
Covers ~500 common ingredients for offline translation without API calls.
"""

EXACT_MATCH = {
    # Oils & fats
    "olive oil": "שמן זית",
    "extra virgin olive oil": "שמן זית כתית מעולה",
    "vegetable oil": "שמן צמחי",
    "canola oil": "שמן קנולה",
    "sunflower oil": "שמן חמניות",
    "sesame oil": "שמן שומשום",
    "coconut oil": "שמן קוקוס",
    "butter": "חמאה",
    "margarine": "מרגרינה",
    "cooking spray": "שמן תרסיס",
    "lard": "שומן חזיר",
    "ghee": "גהי",

    # Meat & protein
    "ground beef": "בקר טחון",
    "ground beef chuck": "בקר טחון",
    "minced beef": "בקר טחון",
    "beef chuck": "כתף בקר",
    "chuck roast": "כתף בקר",
    "brisket": "חזה בקר",
    "ribeye": "אנטריקוט",
    "sirloin": "שייטל",
    "tenderloin": "פילה בקר",
    "ground lamb": "כבש טחון",
    "lamb chops": "צלעות כבש",
    "ground turkey": "הודו טחון",
    "turkey breast": "חזה הודו",
    "chicken breast": "חזה עוף",
    "chicken thigh": "ירך עוף",
    "chicken thighs": "ירך עוף",
    "chicken wings": "כנפיים",
    "whole chicken": "עוף שלם",
    "ground chicken": "עוף טחון",
    "ground pork": "חזיר טחון",
    "pork chops": "צלעות חזיר",
    "bacon": "בייקון",
    "ham": "שינקן",
    "sausage": "נקניק",
    "salami": "סלמי",
    "veal": "עגל",
    "lamb": "כבש",

    # Fish & seafood
    "salmon": "סלמון",
    "tuna": "טונה",
    "tilapia": "טילפיה",
    "cod": "בקלה",
    "shrimp": "שרימפס",
    "prawns": "שרימפס",
    "sea bass": "דניס",
    "trout": "פורל",
    "sardines": "סרדינים",
    "anchovies": "אנשובי",

    # Dairy
    "milk": "חלב",
    "whole milk": "חלב מלא",
    "skim milk": "חלב דל שומן",
    "heavy cream": "שמנת לבישול",
    "heavy whipping cream": "שמנת לבישול",
    "sour cream": "שמנת חמוצה",
    "cream cheese": "גבינת שמנת",
    "cottage cheese": "גבינת קוטג",
    "ricotta": "ריקוטה",
    "ricotta cheese": "גבינת ריקוטה",
    "mozzarella": "מוצרלה",
    "mozzarella cheese": "גבינת מוצרלה",
    "parmesan": "פרמזן",
    "parmesan cheese": "גבינת פרמזן",
    "cheddar": "גבינת צ'דר",
    "feta": "גבינת פטה",
    "gouda": "גבינת גאודה",
    "brie": "גבינת ברי",
    "blue cheese": "גבינה כחולה",
    "halloumi": "חלומי",
    "yogurt": "יוגורט",
    "greek yogurt": "יוגורט יווני",
    "eggs": "ביצים",
    "egg": "ביצה",
    "egg yolk": "חלמון",
    "egg yolks": "חלמונים",
    "egg white": "חלבון",
    "egg whites": "חלבונים",

    # Vegetables
    "onion": "בצל",
    "onions": "בצל",
    "red onion": "בצל אדום",
    "green onion": "בצל ירוק",
    "green onions": "בצל ירוק",
    "scallion": "בצל ירוק",
    "scallions": "בצל ירוק",
    "shallot": "שאלוט",
    "shallots": "שאלוט",
    "garlic": "שום",
    "garlic clove": "שן שום",
    "garlic cloves": "שיני שום",
    "tomato": "עגבנייה",
    "tomatoes": "עגבניות",
    "cherry tomatoes": "עגבניות שרי",
    "sun dried tomatoes": "עגבניות מיובשות",
    "sundried tomatoes": "עגבניות מיובשות",
    "bell pepper": "פלפל צבעוני",
    "red bell pepper": "פלפל אדום",
    "yellow bell pepper": "פלפל צהוב",
    "green bell pepper": "פלפל ירוק",
    "hot pepper": "פלפל חריף",
    "chili pepper": "צ'ילי",
    "chili peppers": "צ'ילי",
    "jalapeño": "חלפיניו",
    "jalapeno": "חלפיניו",
    "carrot": "גזר",
    "carrots": "גזר",
    "celery": "סלרי",
    "celery stalk": "גבעול סלרי",
    "celery stalks": "גבעולי סלרי",
    "potato": "תפוח אדמה",
    "potatoes": "תפוחי אדמה",
    "sweet potato": "בטטה",
    "sweet potatoes": "בטטות",
    "zucchini": "קישוא",
    "eggplant": "חציל",
    "cucumber": "מלפפון",
    "cucumbers": "מלפפונים",
    "spinach": "תרד",
    "kale": "קייל",
    "lettuce": "חסה",
    "broccoli": "ברוקולי",
    "cauliflower": "כרובית",
    "cabbage": "כרוב",
    "red cabbage": "כרוב אדום",
    "mushrooms": "פטריות",
    "mushroom": "פטריות",
    "button mushrooms": "פטריות שמפיניון",
    "champignon": "פטריות שמפיניון",
    "portobello": "פטריות פורטובלו",
    "portobello mushrooms": "פטריות פורטובלו",
    "shiitake": "פטריות שיטאקי",
    "shiitake mushrooms": "פטריות שיטאקי",
    "corn": "תירס",
    "peas": "אפונה",
    "green peas": "אפונה ירוקה",
    "green beans": "שעועית ירוקה",
    "asparagus": "אספרגוס",
    "artichoke": "ארטישוק",
    "leek": "כרישה",
    "leeks": "כרישה",
    "fennel": "שומר",
    "beet": "סלק",
    "beets": "סלק",
    "beetroot": "סלק",
    "radish": "צנון",
    "turnip": "לפת",
    "pumpkin": "דלעת",
    "butternut squash": "דלעת חמאה",
    "avocado": "אבוקדו",
    "olives": "זיתים",
    "black olives": "זיתים שחורים",
    "green olives": "זיתים ירוקים",
    "kalamata olives": "זיתי קלמטה",

    # Fruits
    "lemon": "לימון",
    "lemons": "לימונים",
    "lemon juice": "מיץ לימון",
    "lemon zest": "גרידת לימון",
    "lime": "ליים",
    "lime juice": "מיץ ליים",
    "orange": "תפוז",
    "oranges": "תפוזים",
    "orange juice": "מיץ תפוזים",
    "orange zest": "גרידת תפוז",
    "apple": "תפוח",
    "apples": "תפוחים",
    "banana": "בננה",
    "bananas": "בננות",
    "strawberry": "תות",
    "strawberries": "תות שדה",
    "blueberry": "אוכמניות",
    "blueberries": "אוכמניות",
    "raspberry": "פטל",
    "raspberries": "פטל",
    "mango": "מנגו",
    "pineapple": "אננס",
    "grapes": "ענבים",
    "pomegranate": "רימון",
    "fig": "תאנה",
    "figs": "תאנים",
    "date": "תמר",
    "dates": "תמרים",
    "medjool dates": "תמרי מג'הול",
    "raisins": "צימוקים",
    "dried cranberries": "חמוציות מיובשות",
    "cranberries": "חמוציות",
    "peach": "אפרסק",
    "pear": "אגס",
    "watermelon": "אבטיח",
    "coconut": "קוקוס",
    "dried coconut": "קוקוס מיובש",
    "shredded coconut": "קוקוס מגורד",

    # Grains & pasta
    "flour": "קמח",
    "all purpose flour": "קמח לבן",
    "all-purpose flour": "קמח לבן",
    "whole wheat flour": "קמח מלא",
    "bread flour": "קמח לחם",
    "rice": "אורז",
    "white rice": "אורז לבן",
    "brown rice": "אורז מלא",
    "basmati rice": "אורז בסמטי",
    "jasmine rice": "אורז יסמין",
    "pasta": "פסטה",
    "spaghetti": "ספגטי",
    "penne": "פנה",
    "fusilli": "פוזילי",
    "fettuccine": "פטוצ'יני",
    "lasagna noodles": "לזניה",
    "lasagna sheets": "לזניה",
    "noodles": "אטריות",
    "egg noodles": "אטריות ביצה",
    "couscous": "קוסקוס",
    "quinoa": "קינואה",
    "bulgur": "בורגול",
    "oats": "שיבולת שועל",
    "rolled oats": "שיבולת שועל",
    "breadcrumbs": "פירורי לחם",
    "panko": "פנקו",
    "panko breadcrumbs": "פנקו",
    "bread": "לחם",
    "pita": "פיתה",
    "pita bread": "פיתה",
    "tortilla": "טורטייה",
    "tortillas": "טורטייה",
    "cornmeal": "קמח תירס",
    "semolina": "סולת",
    "cornstarch": "עמילן תירס",
    "corn starch": "עמילן תירס",

    # Legumes
    "chickpeas": "חומוס",
    "lentils": "עדשים",
    "red lentils": "עדשים כתומות",
    "green lentils": "עדשים ירוקות",
    "black beans": "שעועית שחורה",
    "kidney beans": "שעועית אדומה",
    "white beans": "שעועית לבנה",
    "cannellini beans": "שעועית לבנה",
    "tofu": "טופו",
    "edamame": "אדממה",

    # Sauces & condiments
    "tomato sauce": "רוטב עגבניות",
    "tomato paste": "רסק עגבניות",
    "crushed tomatoes": "עגבניות מרוסקות",
    "diced tomatoes": "עגבניות קצוצות",
    "canned tomatoes": "עגבניות משומרות",
    "ketchup": "קטשופ",
    "mustard": "חרדל",
    "dijon mustard": "חרדל דיז'ון",
    "dijon": "חרדל דיז'ון",
    "whole grain mustard": "חרדל גרגירים",
    "mayonnaise": "מיונז",
    "mayo": "מיונז",
    "soy sauce": "רוטב סויה",
    "worcestershire sauce": "רוטב וורצסטרשייר",
    "hot sauce": "רוטב חריף",
    "sriracha": "סרירצ'ה",
    "tahini": "טחינה",
    "hummus": "חומוס",
    "date syrup": "סילאן",
    "silan": "סילאן",
    "honey": "דבש",
    "maple syrup": "סירופ מייפל",
    "vinegar": "חומץ",
    "wine vinegar": "חומץ יין",
    "red wine vinegar": "חומץ יין אדום",
    "white wine vinegar": "חומץ יין לבן",
    "apple cider vinegar": "חומץ תפוחים",
    "balsamic vinegar": "חומץ בלסמי",
    "pesto": "פסטו",
    "fish sauce": "רוטב דגים",
    "oyster sauce": "רוטב צדפות",
    "hoisin sauce": "רוטב הויסין",
    "bbq sauce": "רוטב ברביקיו",
    "barbecue sauce": "רוטב ברביקיו",
    "teriyaki sauce": "רוטב טריאקי",

    # Herbs & spices
    "salt": "מלח",
    "sea salt": "מלח ים",
    "kosher salt": "מלח גס",
    "black pepper": "פלפל שחור",
    "ground black pepper": "פלפל שחור טחון",
    "cracked black pepper": "פלפל שחור גרוס",
    "white pepper": "פלפל לבן",
    "cumin": "כמון",
    "ground cumin": "כמון טחון",
    "paprika": "פפריקה",
    "smoked paprika": "פפריקה מעושנת",
    "sweet paprika": "פפריקה מתוקה",
    "hot paprika": "פפריקה חריפה",
    "turmeric": "כורכום",
    "cinnamon": "קינמון",
    "ground cinnamon": "קינמון טחון",
    "cinnamon stick": "מקל קינמון",
    "cinnamon sticks": "מקלות קינמון",
    "oregano": "אורגנו",
    "dried oregano": "אורגנו יבש",
    "basil": "בזיליקום",
    "fresh basil": "בזיליקום טרי",
    "dried basil": "בזיליקום יבש",
    "thyme": "תימין",
    "fresh thyme": "תימין טרי",
    "dried thyme": "תימין יבש",
    "rosemary": "רוזמרין",
    "fresh rosemary": "רוזמרין טרי",
    "parsley": "פטרוזיליה",
    "fresh parsley": "פטרוזיליה טרייה",
    "cilantro": "כוסברה",
    "fresh cilantro": "כוסברה טרייה",
    "coriander": "כוסברה",
    "ground coriander": "כוסברה טחונה",
    "dill": "שמיר",
    "fresh dill": "שמיר טרי",
    "mint": "נענע",
    "fresh mint": "נענע טרייה",
    "bay leaf": "עלה דפנה",
    "bay leaves": "עלי דפנה",
    "chili flakes": "פלפל צ'ילי",
    "red pepper flakes": "פלפל אדום גרוס",
    "crushed red pepper": "פלפל אדום גרוס",
    "garlic powder": "אבקת שום",
    "onion powder": "אבקת בצל",
    "nutmeg": "אגוז מוסקט",
    "cardamom": "הל",
    "cloves": "ציפורן",
    "ground cloves": "ציפורן טחון",
    "ginger": "זנגביל",
    "fresh ginger": "זנגביל טרי",
    "ground ginger": "זנגביל טחון",
    "vanilla": "וניל",
    "vanilla extract": "תמצית וניל",
    "vanilla bean": "שרביט וניל",
    "italian seasoning": "תבלין איטלקי",
    "mixed herbs": "עשבי תיבול",
    "herbes de provence": "עשבי פרובאנס",
    "za'atar": "זעתר",
    "zaatar": "זעתר",
    "sumac": "סומק",
    "baharat": "בהרט",
    "curry powder": "אבקת קארי",
    "garam masala": "גראם מסאלה",
    "chili powder": "אבקת צ'ילי",
    "cayenne pepper": "פלפל קאיין",
    "allspice": "פלפל אנגלי",
    "star anise": "אניס כוכבי",
    "saffron": "זעפרן",
    "tarragon": "טרגון",
    "sage": "מרווה",
    "lemongrass": "עשב לימון",

    # Baking
    "sugar": "סוכר",
    "white sugar": "סוכר לבן",
    "granulated sugar": "סוכר לבן",
    "brown sugar": "סוכר חום",
    "powdered sugar": "אבקת סוכר",
    "confectioners sugar": "אבקת סוכר",
    "icing sugar": "אבקת סוכר",
    "baking powder": "אבקת אפייה",
    "baking soda": "סודה לשתייה",
    "bicarbonate of soda": "סודה לשתייה",
    "yeast": "שמרים",
    "active dry yeast": "שמרים יבשים",
    "instant yeast": "שמרים מהירים",
    "cocoa powder": "אבקת קקאו",
    "unsweetened cocoa powder": "אבקת קקאו",
    "chocolate": "שוקולד",
    "dark chocolate": "שוקולד מריר",
    "milk chocolate": "שוקולד חלב",
    "white chocolate": "שוקולד לבן",
    "chocolate chips": "שבבי שוקולד",
    "vanilla sugar": "סוכר וניל",
    "gelatin": "ג'לטין",
    "cream of tartar": "אבקת טרטר",

    # Liquids
    "water": "מים",
    "chicken broth": "ציר עוף",
    "beef broth": "ציר בקר",
    "vegetable broth": "ציר ירקות",
    "chicken stock": "ציר עוף",
    "beef stock": "ציר בקר",
    "vegetable stock": "ציר ירקות",
    "white wine": "יין לבן",
    "red wine": "יין אדום",
    "dry white wine": "יין לבן יבש",
    "dry red wine": "יין אדום יבש",
    "beer": "בירה",
    "coconut milk": "חלב קוקוס",
    "almond milk": "חלב שקדים",
    "oat milk": "חלב שיבולת שועל",

    # Nuts & seeds
    "almonds": "שקדים",
    "sliced almonds": "שקדים פרוסים",
    "almond flour": "קמח שקדים",
    "walnuts": "אגוזי מלך",
    "cashews": "קשיו",
    "pine nuts": "צנוברים",
    "sesame seeds": "שומשום",
    "sunflower seeds": "גרעיני חמנייה",
    "pumpkin seeds": "גרעיני דלעת",
    "flax seeds": "זרעי פשתן",
    "flaxseed": "זרעי פשתן",
    "chia seeds": "זרעי צ'יה",
    "peanuts": "בוטנים",
    "peanut butter": "חמאת בוטנים",
    "pecans": "פקאן",
    "pistachios": "פיסטוק",
    "hazelnuts": "אגוזי לוז",
    "macadamia": "מקדמיה",
    "tahini": "טחינה",
}

# Partial match keys — ordered from most specific to least specific.
# Used when exact match fails: if the English key appears as a substring
# in the ingredient name, return the Hebrew translation.
PARTIAL_MATCH_KEYS = [
    ("olive oil", "שמן זית"),
    ("coconut milk", "חלב קוקוס"),
    ("coconut oil", "שמן קוקוס"),
    ("sesame oil", "שמן שומשום"),
    ("sour cream", "שמנת חמוצה"),
    ("cream cheese", "גבינת שמנת"),
    ("tomato paste", "רסק עגבניות"),
    ("tomato sauce", "רוטב עגבניות"),
    ("soy sauce", "רוטב סויה"),
    ("fish sauce", "רוטב דגים"),
    ("hot sauce", "רוטב חריף"),
    ("bell pepper", "פלפל צבעוני"),
    ("black pepper", "פלפל שחור"),
    ("sweet potato", "בטטה"),
    ("green onion", "בצל ירוק"),
    ("red onion", "בצל אדום"),
    ("cherry tomato", "עגבניות שרי"),
    ("beef", "בקר"),
    ("chicken", "עוף"),
    ("turkey", "הודו"),
    ("lamb", "כבש"),
    ("pork", "חזיר"),
    ("salmon", "סלמון"),
    ("tuna", "טונה"),
    ("tomato", "עגבנייה"),
    ("cheese", "גבינה"),
    ("mushroom", "פטריות"),
    ("pepper", "פלפל"),
    ("onion", "בצל"),
    ("garlic", "שום"),
    ("pasta", "פסטה"),
    ("wine", "יין"),
    ("cream", "שמנת"),
    ("flour", "קמח"),
    ("rice", "אורז"),
    ("oil", "שמן"),
    ("vinegar", "חומץ"),
    ("sauce", "רוטב"),
    ("chocolate", "שוקולד"),
    ("sugar", "סוכר"),
    ("milk", "חלב"),
    ("butter", "חמאה"),
    ("lemon", "לימון"),
    ("potato", "תפוח אדמה"),
    ("eggplant", "חציל"),
    ("zucchini", "קישוא"),
    ("broccoli", "ברוקולי"),
    ("spinach", "תרד"),
    ("avocado", "אבוקדו"),
    ("carrot", "גזר"),
    ("egg", "ביצה"),
    ("yogurt", "יוגורט"),
    ("honey", "דבש"),
    ("cinnamon", "קינמון"),
    ("cumin", "כמון"),
    ("paprika", "פפריקה"),
    ("parsley", "פטרוזיליה"),
    ("cilantro", "כוסברה"),
    ("basil", "בזיליקום"),
    ("thyme", "תימין"),
    ("rosemary", "רוזמרין"),
    ("mint", "נענע"),
    ("dill", "שמיר"),
    ("ginger", "זנגביל"),
    ("vanilla", "וניל"),
    ("almond", "שקדים"),
    ("walnut", "אגוזי מלך"),
    ("peanut", "בוטנים"),
    ("sesame", "שומשום"),
    ("coconut", "קוקוס"),
    ("bread", "לחם"),
    ("corn", "תירס"),
    ("bean", "שעועית"),
    ("lentil", "עדשים"),
    ("chickpea", "חומוס"),
    ("broth", "ציר"),
    ("stock", "ציר"),
]


def translate_to_hebrew(name: str) -> str:
    """
    Translate English ingredient name to Hebrew.
    1. Exact match (case-insensitive)
    2. Partial match (substring, most specific first)
    3. Return original if no match (caller should use Claude API as fallback)
    """
    lower = name.lower().strip()

    # Exact match
    if lower in EXACT_MATCH:
        return EXACT_MATCH[lower]

    # Partial match — find best substring hit
    for eng_key, heb_val in PARTIAL_MATCH_KEYS:
        if eng_key in lower:
            return heb_val

    return name  # unchanged — caller will use Claude API as fallback
